import axios from 'axios';

export const FETCH_ORGANIZATION_START = 'FETCH_ORGANIZATION_START';
export const FETCH_ORGANIZATION_SUCCESS = 'FETCH_POKEMON_SUCCESS';
export const FETCH_ORGANIZATION_FAIL = 'FETCH_POKEMON_FAIL';
